### ISSUE TITLE
tmpdir error during BACTOPIA:CALL_VARIANTS

### ISSUE THREAD

**Issue by anwarMZ** [bactopia/bactopia#342]
**Description**
I am getting this `--tmpdir '/localscratch/mzanwar.37952706.0' is not a directory` error during BACTOPIA:CALL_VARIANTS I have attached the log and details below

```
Error executing process > 'BACTOPIA:CALL_VARIANTS (S852 - refseq-genomes)'

Caused by:
  Process `BACTOPIA:CALL_VARIANTS (S852 - refseq-genomes)` terminated with an error exit status (2)

Command executed:

  REFERENCE="refseq-genomes.msh"
  REFERENCE_NAME="refseq-genomes"
  if [[ "refseq-genomes.msh" == "refseq-genomes.msh" ]]; then
      # Get Mash distance (For paired-end, use just R1)
      mash dist -k 31 -s 10000 -t S852_R1.fastq.gz ${REFERENCE} | grep -v "query" | sort -k 2,2 > distances.txt
  
      # Pick top genome and download
      printf "accession\tdistance\tlatest_accession\tupdated\n" > mash-dist.txt
      select-references.py distances.txt 1  >> mash-dist.txt
      grep -v distance mash-dist.txt | cut -f3 > download-list.txt
      ncbi-genome-download bacteria -o ./ -F genbank -p 2 -A download-list.txt             -r 3 
  
      # Move and uncompress genomes
      mkdir genbank_temp
      find refseq -name "*.gbff.gz" | xargs -I {} mv {} genbank_temp/
      rename 's/(GC[AF]_\d+).*/$1/' genbank_temp/*
      ls genbank_temp/ | xargs -I {} sh -c 'gzip -cd genbank_temp/{} > {}.gbk'
      rm -rf genbank_temp/ refseq/
  
      # Update variables
      REFERENCE=$(ls *.gbk)
      REFERENCE_NAME=$(basename ${REFERENCE} .gbk)
  
      # Capture version
      mash --version > mash.version.txt 2>&1
      ncbi-genome-download --version > ncbi-genome-download.version.txt 2>&1
  fi
  
  snippy --R1 S852_R1.fastq.gz --R2 S852_R2.fastq.gz         --ref ${REFERENCE}         --cpus 2         --ram 7         --outdir ${REFERENCE_NAME}         --prefix S852         --mapqual 60         --basequal 13         --mincov 10         --minfrac 0         --minqual 100         --maxsoft 10  
  mv ${REFERENCE_NAME}/S852.log ./
  
  # Add GenBank annotations
  vcf-annotator ${REFERENCE_NAME}/S852.vcf ${REFERENCE} --output ${REFERENCE_NAME}/S852.annotated.vcf
  
  # Get per-base coverage
  grep "^##contig" ${REFERENCE_NAME}/S852.vcf > ${REFERENCE_NAME}/S852.full-coverage.txt
  genomeCoverageBed -ibam ${REFERENCE_NAME}/S852.bam -d >> ${REFERENCE_NAME}/S852.full-coverage.txt
  cleanup-coverage.py ${REFERENCE_NAME}/S852.full-coverage.txt > ${REFERENCE_NAME}/S852.coverage.txt
  rm ${REFERENCE_NAME}/S852.full-coverage.txt
  
  # Mask low coverage regions
  mask-consensus.py S852 ${REFERENCE_NAME}         ${REFERENCE_NAME}/S852.consensus.subs.fa         ${REFERENCE_NAME}/S852.subs.vcf         ${REFERENCE_NAME}/S852.coverage.txt         --mincov 10 > ${REFERENCE_NAME}/S852.consensus.subs.masked.fa
  
  # Clean Up
  rm -rf ${REFERENCE_NAME}/reference ${REFERENCE_NAME}/ref.fa* ${REFERENCE_NAME}/S852.vcf.gz*
  
  if [[ "refseq-genomes.msh" == "refseq-genomes.msh" ]]; then
      mv distances.txt ${REFERENCE_NAME}/mash-distances.txt
      mv mash-dist.txt ${REFERENCE_NAME}/mash-selected.txt
      mv download-list.txt ${REFERENCE_NAME}/mash-downloaded.txt
      mv ${REFERENCE} ${REFERENCE_NAME}/
  fi
  
  if [[ false == "false" ]]; then
      find ${REFERENCE_NAME}/ -type f |             grep -v -E "\.bam$|\.bai$|\.log$|\.txt$|\.html$|\.tab$" |             xargs -I {} pigz -n --best -p 2 {}
      pigz -n --best -p 2 ${REFERENCE_NAME}/S852.coverage.txt
  fi
  
  mkdir results
  mv ${REFERENCE_NAME}/ results/
  
  # Capture versions
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIA:CALL_VARIANTS":
      bedtools: $(echo $(bedtools --version 2>&1) | sed 's/bedtools v//')
      mash: $(echo $(mash 2>&1) | sed 's/^.*Mash version //;s/ .*$//')
      ncbi-genome-download: $(echo $(ncbi-genome-download --version 2>&1))
      pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
      snippy: $(echo $(snippy --version 2>&1) | sed 's/snippy //')
      vcf-annotator: $(echo $(vcf-annotator --version 2>&1) | sed 's/vcf-annotator.py //')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  mash: Relink `/opt/conda/envs/bactopia-call_variants/bin/../lib/./libgfortran.so.5' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
  Sketching S852_R1.fastq.gz (provide sketch file made with "mash sketch" to skip)...done.
  [00:01:11] This is snippy 4.6.0
  [00:01:11] Written by Torsten Seemann
  [00:01:11] Obtained from https://github.com/tseemann/snippy
  [00:01:11] Detected operating system: linux
  [00:01:11] Enabling bundled linux tools.
  [00:01:11] Found bwa - /opt/conda/envs/bactopia-call_variants/bin/bwa
  [00:01:11] Found bcftools - /opt/conda/envs/bactopia-call_variants/bin/bcftools
  [00:01:11] Found samtools - /opt/conda/envs/bactopia-call_variants/bin/samtools
  [00:01:11] Found java - /opt/conda/envs/bactopia-call_variants/bin/java
  [00:01:11] Found snpEff - /opt/conda/envs/bactopia-call_variants/bin/snpEff
  [00:01:11] Found samclip - /opt/conda/envs/bactopia-call_variants/bin/samclip
  [00:01:11] Found seqtk - /opt/conda/envs/bactopia-call_variants/bin/seqtk
  [00:01:11] Found parallel - /opt/conda/envs/bactopia-call_variants/bin/parallel
  [00:01:11] Found freebayes - /opt/conda/envs/bactopia-call_variants/bin/freebayes
  [00:01:11] Found freebayes-parallel - /opt/conda/envs/bactopia-call_variants/bin/freebayes-parallel
  [00:01:11] Found fasta_generate_regions.py - /opt/conda/envs/bactopia-call_variants/bin/fasta_generate_regions.py
  [00:01:11] Found vcfstreamsort - /opt/conda/envs/bactopia-call_variants/bin/vcfstreamsort
  [00:01:11] Found vcfuniq - /opt/conda/envs/bactopia-call_variants/bin/vcfuniq
  [00:01:11] Found vcffirstheader - /opt/conda/envs/bactopia-call_variants/bin/vcffirstheader
  [00:01:11] Found gzip - /bin/gzip
  [00:01:11] Found vt - /opt/conda/envs/bactopia-call_variants/bin/vt
  [00:01:11] Found snippy-vcf_to_tab - /opt/conda/envs/bactopia-call_variants/bin/snippy-vcf_to_tab
  [00:01:11] Found snippy-vcf_report - /opt/conda/envs/bactopia-call_variants/bin/snippy-vcf_report
  [00:01:11] Checking version: samtools --version is >= 1.7 - ok, have 1.15
  [00:01:11] Checking version: bcftools --version is >= 1.7 - ok, have 1.15
  [00:01:11] Checking version: freebayes --version is >= 1.1 - ok, have 1.3.2
  [00:01:13] Checking version: snpEff -version is >= 4.3 - ok, have 5.0
  [00:01:13] Checking version: bwa is >= 0.7.12 - ok, have 0.7.17
  [00:01:13] Using reference: GCF_009763525.gbk
  [00:01:13] Treating reference as 'genbank' format.
  [00:01:13] Will use 2 CPU cores.
  [00:01:13] Using read file: /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/21/5ac8fa279b0ba6326d6abc94df558c/results/S852_R1.fastq.gz
  [00:01:13] Using read file: /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/21/5ac8fa279b0ba6326d6abc94df558c/results/S852_R2.fastq.gz
  [00:01:13] --tmpdir '/localscratch/mzanwar.37952706.0' is not a directory

Work dir:
  /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/dd/a32c59a651f78032b979230716b6aa

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

```

**Steps to Reproduce**

`nextflow run main.nf -profile singularity --R1 S852_R1.fastq.gz --R2 S852_R2.fastq.gz --sample S852 --datasets ../datasets/ --species "Vibrio parahaemolyticus" --coverage 100 --genome_size median --outdir ./results -qs 2 --run_checkm `

**Execution Environment**

- Bactopia Version: `v2.1.0`
- OS: Linux-based cluster
- Environment: Singularity container

**Comment by rpetit3** [comment]
Looks like Snippy defaults to the `$TMPDIR` environment variable. Let me see about making the tmp directory in the same folder as where the files are staged.

I'll update soon

**Comment by rpetit3** [comment]
I think I have the temp directory issue solved with (https://github.com/bactopia/bactopia/commit/0856bf3e2881a92fc5b78ff7c0b3abd696d09697). Basically just going to use the folder the files are staged in. Its only used for bwa/samtools sort/view etc...

This is currently available from my dev build:
```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
conda activate bactopia-dev
```

Now for the Prokka issue, doesn't look like we have the option to change the temp directory for Prokka. Is there maybe a `prokka.log` file? I'm hoping it has a bit more info to help us figure out why parallel failed (although maybe not! it sends stderr to /dev/null)

**Comment by anwarMZ** [comment]
> Now for the Prokka issue, doesn't look like we have the option to change the temp directory for Prokka. Is there maybe a prokka.log file? I'm hoping it has a bit more info to help us figure out why parallel failed (although maybe not! it sends stderr to /dev/null)

Additionally, the problem for genome_annotation remains the same. I checked the log isn't there. I was wondering is this due to hardcoding the number of threads used by gnu parallel? I may be wrong but just trying to figure out why is there no other error in the log as above.

**Comment by rpetit3** [comment]
For the call variants: anything useful in `GCF_009763525/S852.log` that is mentioned?

For annotate_genome, the number of cpus is set by `--max_cpus`. I'm curious does the assembly look OK for this sample?

Also, what's the command being used when executing bactopia?

**Comment by anwarMZ** [comment]
for call variants `GCF_009763525/S852.log`
```

### echo snippy 4.6.0
### cd /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/c6/8f3e8011ddc6e563cfc58639fa98eb

### /opt/conda/envs/bactopia-call_variants/bin/snippy --R1 S852_R1.fastq.gz --R2 S852_R2.fastq.gz --ref GCF_009763525.gbk --cpus 3 --ram 7 --outdir GCF_009763525 --prefix S852 --mapqual 60 --basequal 13 --mincov 10 --minfrac 0 --minqual 100 --tmpdir tmp_snippy/ --maxsoft 10

### samtools faidx reference/ref.fa


### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.08 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 1.44 seconds elapse.
[bwa_index] Update BWT... 0.06 sec
[bwa_index] Pack forward-only FASTA... 0.05 sec
[bwa_index] Construct SA from BWT and Occ... 0.78 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 5.711 sec; CPU: 2.415 sec

### mkdir -p reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### ln -sf reference/ref.fa .


### ln -sf reference/ref.fa.fai .


### mkdir -p reference/ref && gzip -c reference/ref.gff > reference/ref/genes.gff.gz


### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

### bwa mem  -Y -M -R '@RG\tID:GCF_009763525\tSM:GCF_009763525' -t 3 reference/ref.fa /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/05/6699c5b0ae1a306c05c331a54b2055/results/S852_R1.fastq.gz /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/05/6699c5b0ae1a306c05c331a54b2055/results/S852_R2.fastq.gz | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/c6/8f3e8011ddc6e563cfc58639fa98eb/tmp_snippy --threads 0 -m 7000M | samtools fixmate -m --threads 0 - - | samtools sort -l 0 -T /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/c6/8f3e8011ddc6e563cfc58639fa98eb/tmp_snippy --threads 0 -m 7000M | samtools markdup -T /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/c6/8f3e8011ddc6e563cfc58639fa98eb/tmp_snippy --threads 0 -r -s - - > S852.bam

COMMAND: samtools markdup -T /project/6007413/mzanwar/projects/UPCOAST-V/bactopia/work/c6/8f3e8011ddc6e563cfc58639fa98eb/tmp_snippy --threads 0 -r -s - -
READ: 3455535
WRITTEN: 3070045
EXCLUDED: 32241
EXAMINED: 3423294
PAIRED: 3402542
SINGLE: 20752
DUPLICATE PAIR: 372062
DUPLICATE SINGLE: 13428
DUPLICATE PAIR OPTICAL: 0
DUPLICATE SINGLE OPTICAL: 0
DUPLICATE NON PRIMARY: 0
DUPLICATE NON PRIMARY OPTICAL: 0
DUPLICATE PRIMARY TOTAL: 385490
DUPLICATE TOTAL: 385490
ESTIMATED_LIBRARY_SIZE: 7201065

### samtools index S852.bam


### fasta_generate_regions.py reference/ref.fa.fai 1049018 > reference/ref.txt


### freebayes-parallel reference/ref.txt 3 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 10 --min-repeat-entropy 1.0 -q 13 -m 60 --strict-vcf   -f reference/ref.fa S852.bam > S852.raw.vcf

Error in tempfile() using template /localscratch/mzanwar.38155235.0/parXXXXX.par: Parent directory (/localscratch/mzanwar.38155235.0/) does not exist at /opt/conda/envs/bactopia-call_variants/bin/parallel line 5884.
```
Looks like the issue is still with the `tmpfile()`, this time in `freebayes`?

**Comment by rpetit3** [comment]
_Looks like the issue is still with the tmpfile(), this time in freebayes?_

Yep, totally a tmpdir issue. I wonder if for your cluster you'll need to set the $TMPDIR/$TMP variable to some other spot.  Although I'm not sure why `/localscratch/mzanwar.38155235.0/` doesn't exist. 

Given Prokka also failed on a parallel step. I wonder if it too is related to the TMPDIR


What's the job scheduler on your cluster?

**Comment by anwarMZ** [comment]
cluster is SLURM based, for testing, I am running it in an interactive mode by allocating specific resources. 
`salloc --time=4:0:0 --ntasks=4 --account=xxx-mzanwar-xx --mem-per-cpu=8G`

I checked my $TMPDIR and its different from where it tries to make the file - quite strange!

```
echo $TMPDIR
/tmp
```

maybe check with cluster support?

**Comment by rpetit3** [comment]
Let's try this:

```
bactopia \
  --R1 S852_L001_R1_001.fastq.gz \
  --R2 S852_L001_R2_001.fastq.gz \
  --sample S852 \
  --datasets ../datasets/ \
  --species "Vibrio parahaemolyticus" \
  --coverage 100 \
  --genome_size median \
  --outdir ./results \
  --run_checkm \
  -resume \
  -profile slurm \
  --queue "<YOUR_CLUSTER_QUEUE>" \
  --clusterOptions "--account=xxx-mzanwar-xx"
```

Running this from the login node, would allow nextflow to submit the jobs to the scheduler

**Comment by rpetit3** [comment]
important options here are 
```
  -profile slurm \
  --queue "<YOUR_CLUSTER_QUEUE>" \
  --clusterOptions "--account=xxx-mzanwar-xx"
```

Options are described here: https://github.com/bactopia/bactopia/blob/master/conf/schema/profiles/slurm.json

or `bactopia -profile slurm --help`

**Comment by anwarMZ** [comment]
ok I am running into JAVA heap error - I believe lots of people have discussed this, any suggestions 

command from head node `nextflow run main.nf --R1 S852_L001_R1_001.fastq.gz --R2 S852_L001_R2_001.fastq.gz --sample S852 --datasets ../datasets/ --species "Vibrio parahaemolyticus" --coverage 100 --genome_size median --outdir ./results --run_checkm -resume -profile slurm --clusterOptions "--account=xxx-mzanwar-xx"`

I also increased by `export _JAVA_OPTIONS="-Xms256m -Xmx8g"`

```
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
Picked up _JAVA_OPTIONS: -Xms256m -Xmx8g
Error occurred during initialization of VM
Could not reserve enough space for 8388608KB object heap
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/java/11.0.2/bin/java
 NXF_OPTS: 
```

**Comment by rpetit3** [comment]
Hmmm, what's the total memory on the head node? 

This might have some useful things to try: https://github.com/nextflow-io/nextflow/issues/1620

**Comment by anwarMZ** [comment]
not sure about the total memory on the head node. Still struggling to run the workflow with SLURM profile and get the same error. 
```

[b4/ef6f97] process > BACTOPIA:GATHER_SAMPLES (CF... [ 50%] 1 of 2, failed: 1...
[-        ] process > BACTOPIA:QC_READS              -
[-        ] process > BACTOPIA:ASSEMBLE_GENOME       -
[-        ] process > BACTOPIA:ASSEMBLY_QC           -
[-        ] process > BACTOPIA:ANNOTATE_GENOME       -
[-        ] process > BACTOPIA:MINMER_SKETCH         -
[-        ] process > BACTOPIA:ANTIMICROBIAL_RESI... -
[-        ] process > BACTOPIA:MINMER_QUERY          -
[-        ] process > BACTOPIA:BLAST                 -
[-        ] process > BACTOPIA:CALL_VARIANTS         -
[-        ] process > BACTOPIA:MAPPING_QUERY         -
[-        ] process > BACTOPIA:SEQUENCE_TYPE         -
[-        ] process > BACTOPIA:CUSTOM_DUMPSOFTWAR... -
[b4/ef6f97] NOTE: Error submitting process 'BACTOPIA:GATHER_SAMPLES (CFIABU2018_0411_1_S852)' for execution -- Execution is retried (1)
```

**Comment by anwarMZ** [comment]
I will also check with nf-core, if they have any recommendation

**Comment by rpetit3** [comment]
What's the `.nextflow.log` file look like? Happy to take this offline if you'd prefer to share the files through email

**Comment by anwarMZ** [comment]
Just sent you a msg through nf-core slack. we can exchange files there more easily. The mail client may not allow sending specific files.

**Comment by rpetit3** [comment]
@anwarMZ going to go ahead an close this since we pretty much got it figured out offline

**Comment by kimandrews** [comment]
I'm trying to run the snippy workflow using Bactopia v.3.1.0 with Singularity on a Linux cluster and getting a similar error as was described earlier in this issue:  `--tmpdir '/loc/scratch/64015251' is not a directory`

I see that the fix [described above](https://github.com/bactopia/bactopia/issues/342#issuecomment-1170330861) in https://github.com/bactopia/bactopia/commit/0856bf3e2881a92fc5b78ff7c0b3abd696d09697 is not present in the [snippy main.nf](https://github.com/bactopia/bactopia/blob/474be2d4d0694c392436e4bda17d0b1e6814389b/subworkflows/local/snippy/main.nf) and wonder if adding that in could solve the issue?

Here is my command:
`bactopia --wf snippy --bactopia ./out/cleaned --accession GCF_000195955.2  -profile singularity --nfconfig my_config.nf`

Here are the log details:

```
Command error:
  [17:02:57] This is snippy 4.6.0
  [17:02:57] Written by Torsten Seemann
  [17:02:57] Obtained from https://github.com/tseemann/snippy
  [17:02:57] Detected operating system: linux
  [17:02:57] Enabling bundled linux tools.
  [17:02:57] Found bwa - /usr/local/bin/bwa
  [17:02:57] Found bcftools - /usr/local/bin/bcftools
  [17:02:57] Found samtools - /usr/local/bin/samtools
  [17:02:57] Found java - /usr/local/bin/java
  [17:02:57] Found snpEff - /usr/local/bin/snpEff
  [17:02:57] Found samclip - /usr/local/bin/samclip
  [17:02:57] Found seqtk - /usr/local/bin/seqtk
  [17:02:57] Found parallel - /usr/local/bin/parallel
  [17:02:57] Found freebayes - /usr/local/bin/freebayes
  [17:02:57] Found freebayes-parallel - /usr/local/bin/freebayes-parallel
  [17:02:57] Found fasta_generate_regions.py - /usr/local/bin/fasta_generate_regions.py
  [17:02:57] Found vcfstreamsort - /usr/local/bin/vcfstreamsort
  [17:02:57] Found vcfuniq - /usr/local/bin/vcfuniq
  [17:02:57] Found vcffirstheader - /usr/local/bin/vcffirstheader
  [17:02:57] Found gzip - /usr/bin/gzip
  [17:02:57] Found vt - /usr/local/bin/vt
  [17:02:57] Found snippy-vcf_to_tab - /usr/local/bin/snippy-vcf_to_tab
  [17:02:57] Found snippy-vcf_report - /usr/local/bin/snippy-vcf_report
  [17:02:57] Checking version: samtools --version is >= 1.7 - ok, have 1.19
  [17:02:57] Checking version: bcftools --version is >= 1.7 - ok, have 1.14
  [17:02:57] Checking version: freebayes --version is >= 1.1 - ok, have 1.3.6
  [17:02:58] Checking version: snpEff -version is >= 4.3 - ok, have 4.5
  [17:02:58] Checking version: bwa is >= 0.7.12 - ok, have 0.7.17
  [17:02:58] Using reference: GCF_000195955.2_ASM19595v2_genomic.gbff
  [17:02:58] Treating reference as 'genbank' format.
  [17:02:58] Will use 1 CPU cores.
  [17:02:58] Using read file: /home/andrewsk/tb/test6_tb/out/cleanyerreads_01/SRX24620628/main/qc/SRX24620628_R1.fastq.gz
  [17:02:58] Using read file: /home/andrewsk/tb/test6_tb/out/cleanyerreads_01/SRX24620628/main/qc/SRX24620628_R2.fastq.gz
  [17:02:58] --tmpdir '/loc/scratch/64015251' is not a directory
```

**Comment by kimandrews** [comment]
Thanks! I created a dev environment and re-ran the command. This time I got further through the snippy workflow, but eventually encountered this error message:

```
### freebayes-parallel reference/ref.txt 1 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 10 --min-repeat-entropy 1.0 -q 13 -m 60 --strict-vcf   -f reference/ref.fa SRX8866192.bam > SRX8866192.raw.vcf

Error in tempfile() using template /loc/scratch/64260705/parXXXXX.par: Parent directory (/loc/scratch/64260705/) does not exist at /usr/local/bin/parallel line 6343.
```
